/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TvIndexRouteImport } from './routes/tv.index'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated/users'
import { Route as AuthenticatedSettlementsRouteImport } from './routes/_authenticated/settlements'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedLeaderboardRouteImport } from './routes/_authenticated/leaderboard'
import { Route as AuthenticatedHubRouteImport } from './routes/_authenticated/hub'
import { Route as AuthenticatedHistoryRouteImport } from './routes/_authenticated/history'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedChatsRouteImport } from './routes/_authenticated/chats'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as AuthenticatedPlayersIndexRouteImport } from './routes/_authenticated/players.index'
import { Route as AuthenticatedPlayIndexRouteImport } from './routes/_authenticated/play.index'
import { Route as TvGameGameIdRouteImport } from './routes/tv.game.$gameId'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as AuthenticatedPlayersIdRouteImport } from './routes/_authenticated/players.$id'
import { Route as AuthenticatedPlaySettlementsRouteImport } from './routes/_authenticated/play.settlements'
import { Route as AuthenticatedPlayAccountRouteImport } from './routes/_authenticated/play.account'
import { Route as AuthenticatedPlayIdRouteImport } from './routes/_authenticated/play.$id'
import { Route as AuthenticatedNightsNewRouteImport } from './routes/_authenticated/nights.new'
import { Route as AuthenticatedNightsIdRouteImport } from './routes/_authenticated/nights.$id'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as ApiPublicHooksRsvpRouteImport } from './routes/api/public/hooks/rsvp'
import { Route as ApiPublicHooksPushRemindersRouteImport } from './routes/api/public/hooks/push-reminders'
import { Route as ApiPublicHooksNewUserRouteImport } from './routes/api/public/hooks/new-user'
import { Route as AuthenticatedPlayersWalkinNameRouteImport } from './routes/_authenticated/players.walkin.$name'
import { Route as AuthenticatedPlayBjIdRouteImport } from './routes/_authenticated/play.bj.$id'
import { Route as AuthenticatedNightsIdResultsRouteImport } from './routes/_authenticated/nights.$id.results'
import { Route as AuthenticatedNightsIdEditRouteImport } from './routes/_authenticated/nights.$id.edit'
import { Route as AuthenticatedNightsIdChatRouteImport } from './routes/_authenticated/nights.$id.chat'
import { Route as AuthenticatedGameGameIdTvControlRouteImport } from './routes/_authenticated/game.$gameId.tv-control'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TvIndexRoute = TvIndexRouteImport.update({
  id: '/tv/',
  path: '/tv/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettlementsRoute =
  AuthenticatedSettlementsRouteImport.update({
    id: '/settlements',
    path: '/settlements',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLeaderboardRoute =
  AuthenticatedLeaderboardRouteImport.update({
    id: '/leaderboard',
    path: '/leaderboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHubRoute = AuthenticatedHubRouteImport.update({
  id: '/hub',
  path: '/hub',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHistoryRoute = AuthenticatedHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChatsRoute = AuthenticatedChatsRouteImport.update({
  id: '/chats',
  path: '/chats',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedPlayersIndexRoute =
  AuthenticatedPlayersIndexRouteImport.update({
    id: '/players/',
    path: '/players/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPlayIndexRoute = AuthenticatedPlayIndexRouteImport.update({
  id: '/play/',
  path: '/play/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const TvGameGameIdRoute = TvGameGameIdRouteImport.update({
  id: '/tv/game/$gameId',
  path: '/tv/game/$gameId',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPlayersIdRoute = AuthenticatedPlayersIdRouteImport.update({
  id: '/players/$id',
  path: '/players/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlaySettlementsRoute =
  AuthenticatedPlaySettlementsRouteImport.update({
    id: '/play/settlements',
    path: '/play/settlements',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPlayAccountRoute =
  AuthenticatedPlayAccountRouteImport.update({
    id: '/play/account',
    path: '/play/account',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPlayIdRoute = AuthenticatedPlayIdRouteImport.update({
  id: '/play/$id',
  path: '/play/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNightsNewRoute = AuthenticatedNightsNewRouteImport.update({
  id: '/nights/new',
  path: '/nights/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNightsIdRoute = AuthenticatedNightsIdRouteImport.update({
  id: '/nights/$id',
  path: '/nights/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksRsvpRoute = ApiPublicHooksRsvpRouteImport.update({
  id: '/api/public/hooks/rsvp',
  path: '/api/public/hooks/rsvp',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksPushRemindersRoute =
  ApiPublicHooksPushRemindersRouteImport.update({
    id: '/api/public/hooks/push-reminders',
    path: '/api/public/hooks/push-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksNewUserRoute = ApiPublicHooksNewUserRouteImport.update({
  id: '/api/public/hooks/new-user',
  path: '/api/public/hooks/new-user',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPlayersWalkinNameRoute =
  AuthenticatedPlayersWalkinNameRouteImport.update({
    id: '/players/walkin/$name',
    path: '/players/walkin/$name',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPlayBjIdRoute = AuthenticatedPlayBjIdRouteImport.update({
  id: '/play/bj/$id',
  path: '/play/bj/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNightsIdResultsRoute =
  AuthenticatedNightsIdResultsRouteImport.update({
    id: '/results',
    path: '/results',
    getParentRoute: () => AuthenticatedNightsIdRoute,
  } as any)
const AuthenticatedNightsIdEditRoute =
  AuthenticatedNightsIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthenticatedNightsIdRoute,
  } as any)
const AuthenticatedNightsIdChatRoute =
  AuthenticatedNightsIdChatRouteImport.update({
    id: '/chat',
    path: '/chat',
    getParentRoute: () => AuthenticatedNightsIdRoute,
  } as any)
const AuthenticatedGameGameIdTvControlRoute =
  AuthenticatedGameGameIdTvControlRouteImport.update({
    id: '/game/$gameId/tv-control',
    path: '/game/$gameId/tv-control',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/chats': typeof AuthenticatedChatsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/hub': typeof AuthenticatedHubRoute
  '/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/settlements': typeof AuthenticatedSettlementsRoute
  '/users': typeof AuthenticatedUsersRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/tv/': typeof TvIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/nights/$id': typeof AuthenticatedNightsIdRouteWithChildren
  '/nights/new': typeof AuthenticatedNightsNewRoute
  '/play/$id': typeof AuthenticatedPlayIdRoute
  '/play/account': typeof AuthenticatedPlayAccountRoute
  '/play/settlements': typeof AuthenticatedPlaySettlementsRoute
  '/players/$id': typeof AuthenticatedPlayersIdRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/tv/game/$gameId': typeof TvGameGameIdRoute
  '/play/': typeof AuthenticatedPlayIndexRoute
  '/players/': typeof AuthenticatedPlayersIndexRoute
  '/game/$gameId/tv-control': typeof AuthenticatedGameGameIdTvControlRoute
  '/nights/$id/chat': typeof AuthenticatedNightsIdChatRoute
  '/nights/$id/edit': typeof AuthenticatedNightsIdEditRoute
  '/nights/$id/results': typeof AuthenticatedNightsIdResultsRoute
  '/play/bj/$id': typeof AuthenticatedPlayBjIdRoute
  '/players/walkin/$name': typeof AuthenticatedPlayersWalkinNameRoute
  '/api/public/hooks/new-user': typeof ApiPublicHooksNewUserRoute
  '/api/public/hooks/push-reminders': typeof ApiPublicHooksPushRemindersRoute
  '/api/public/hooks/rsvp': typeof ApiPublicHooksRsvpRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/chats': typeof AuthenticatedChatsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/hub': typeof AuthenticatedHubRoute
  '/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/settlements': typeof AuthenticatedSettlementsRoute
  '/users': typeof AuthenticatedUsersRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/tv': typeof TvIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/nights/$id': typeof AuthenticatedNightsIdRouteWithChildren
  '/nights/new': typeof AuthenticatedNightsNewRoute
  '/play/$id': typeof AuthenticatedPlayIdRoute
  '/play/account': typeof AuthenticatedPlayAccountRoute
  '/play/settlements': typeof AuthenticatedPlaySettlementsRoute
  '/players/$id': typeof AuthenticatedPlayersIdRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/tv/game/$gameId': typeof TvGameGameIdRoute
  '/play': typeof AuthenticatedPlayIndexRoute
  '/players': typeof AuthenticatedPlayersIndexRoute
  '/game/$gameId/tv-control': typeof AuthenticatedGameGameIdTvControlRoute
  '/nights/$id/chat': typeof AuthenticatedNightsIdChatRoute
  '/nights/$id/edit': typeof AuthenticatedNightsIdEditRoute
  '/nights/$id/results': typeof AuthenticatedNightsIdResultsRoute
  '/play/bj/$id': typeof AuthenticatedPlayBjIdRoute
  '/players/walkin/$name': typeof AuthenticatedPlayersWalkinNameRoute
  '/api/public/hooks/new-user': typeof ApiPublicHooksNewUserRoute
  '/api/public/hooks/push-reminders': typeof ApiPublicHooksPushRemindersRoute
  '/api/public/hooks/rsvp': typeof ApiPublicHooksRsvpRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/chats': typeof AuthenticatedChatsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/history': typeof AuthenticatedHistoryRoute
  '/_authenticated/hub': typeof AuthenticatedHubRoute
  '/_authenticated/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/settlements': typeof AuthenticatedSettlementsRoute
  '/_authenticated/users': typeof AuthenticatedUsersRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/tv/': typeof TvIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/_authenticated/nights/$id': typeof AuthenticatedNightsIdRouteWithChildren
  '/_authenticated/nights/new': typeof AuthenticatedNightsNewRoute
  '/_authenticated/play/$id': typeof AuthenticatedPlayIdRoute
  '/_authenticated/play/account': typeof AuthenticatedPlayAccountRoute
  '/_authenticated/play/settlements': typeof AuthenticatedPlaySettlementsRoute
  '/_authenticated/players/$id': typeof AuthenticatedPlayersIdRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/tv/game/$gameId': typeof TvGameGameIdRoute
  '/_authenticated/play/': typeof AuthenticatedPlayIndexRoute
  '/_authenticated/players/': typeof AuthenticatedPlayersIndexRoute
  '/_authenticated/game/$gameId/tv-control': typeof AuthenticatedGameGameIdTvControlRoute
  '/_authenticated/nights/$id/chat': typeof AuthenticatedNightsIdChatRoute
  '/_authenticated/nights/$id/edit': typeof AuthenticatedNightsIdEditRoute
  '/_authenticated/nights/$id/results': typeof AuthenticatedNightsIdResultsRoute
  '/_authenticated/play/bj/$id': typeof AuthenticatedPlayBjIdRoute
  '/_authenticated/players/walkin/$name': typeof AuthenticatedPlayersWalkinNameRoute
  '/api/public/hooks/new-user': typeof ApiPublicHooksNewUserRoute
  '/api/public/hooks/push-reminders': typeof ApiPublicHooksPushRemindersRoute
  '/api/public/hooks/rsvp': typeof ApiPublicHooksRsvpRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/mcp'
    | '/sitemap.xml'
    | '/.well-known/oauth-protected-resource'
    | '/chats'
    | '/dashboard'
    | '/history'
    | '/hub'
    | '/leaderboard'
    | '/notifications'
    | '/profile'
    | '/settlements'
    | '/users'
    | '/email/unsubscribe'
    | '/tv/'
    | '/.lovable/oauth/consent'
    | '/nights/$id'
    | '/nights/new'
    | '/play/$id'
    | '/play/account'
    | '/play/settlements'
    | '/players/$id'
    | '/lovable/email/suppression'
    | '/tv/game/$gameId'
    | '/play/'
    | '/players/'
    | '/game/$gameId/tv-control'
    | '/nights/$id/chat'
    | '/nights/$id/edit'
    | '/nights/$id/results'
    | '/play/bj/$id'
    | '/players/walkin/$name'
    | '/api/public/hooks/new-user'
    | '/api/public/hooks/push-reminders'
    | '/api/public/hooks/rsvp'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/mcp'
    | '/sitemap.xml'
    | '/.well-known/oauth-protected-resource'
    | '/chats'
    | '/dashboard'
    | '/history'
    | '/hub'
    | '/leaderboard'
    | '/notifications'
    | '/profile'
    | '/settlements'
    | '/users'
    | '/email/unsubscribe'
    | '/tv'
    | '/.lovable/oauth/consent'
    | '/nights/$id'
    | '/nights/new'
    | '/play/$id'
    | '/play/account'
    | '/play/settlements'
    | '/players/$id'
    | '/lovable/email/suppression'
    | '/tv/game/$gameId'
    | '/play'
    | '/players'
    | '/game/$gameId/tv-control'
    | '/nights/$id/chat'
    | '/nights/$id/edit'
    | '/nights/$id/results'
    | '/play/bj/$id'
    | '/players/walkin/$name'
    | '/api/public/hooks/new-user'
    | '/api/public/hooks/push-reminders'
    | '/api/public/hooks/rsvp'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/mcp'
    | '/sitemap.xml'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/chats'
    | '/_authenticated/dashboard'
    | '/_authenticated/history'
    | '/_authenticated/hub'
    | '/_authenticated/leaderboard'
    | '/_authenticated/notifications'
    | '/_authenticated/profile'
    | '/_authenticated/settlements'
    | '/_authenticated/users'
    | '/email/unsubscribe'
    | '/tv/'
    | '/.lovable/oauth/consent'
    | '/_authenticated/nights/$id'
    | '/_authenticated/nights/new'
    | '/_authenticated/play/$id'
    | '/_authenticated/play/account'
    | '/_authenticated/play/settlements'
    | '/_authenticated/players/$id'
    | '/lovable/email/suppression'
    | '/tv/game/$gameId'
    | '/_authenticated/play/'
    | '/_authenticated/players/'
    | '/_authenticated/game/$gameId/tv-control'
    | '/_authenticated/nights/$id/chat'
    | '/_authenticated/nights/$id/edit'
    | '/_authenticated/nights/$id/results'
    | '/_authenticated/play/bj/$id'
    | '/_authenticated/players/walkin/$name'
    | '/api/public/hooks/new-user'
    | '/api/public/hooks/push-reminders'
    | '/api/public/hooks/rsvp'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  McpRoute: typeof McpRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  TvIndexRoute: typeof TvIndexRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  TvGameGameIdRoute: typeof TvGameGameIdRoute
  ApiPublicHooksNewUserRoute: typeof ApiPublicHooksNewUserRoute
  ApiPublicHooksPushRemindersRoute: typeof ApiPublicHooksPushRemindersRoute
  ApiPublicHooksRsvpRoute: typeof ApiPublicHooksRsvpRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tv/': {
      id: '/tv/'
      path: '/tv'
      fullPath: '/tv/'
      preLoaderRoute: typeof TvIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settlements': {
      id: '/_authenticated/settlements'
      path: '/settlements'
      fullPath: '/settlements'
      preLoaderRoute: typeof AuthenticatedSettlementsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leaderboard': {
      id: '/_authenticated/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof AuthenticatedLeaderboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hub': {
      id: '/_authenticated/hub'
      path: '/hub'
      fullPath: '/hub'
      preLoaderRoute: typeof AuthenticatedHubRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/history': {
      id: '/_authenticated/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AuthenticatedHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chats': {
      id: '/_authenticated/chats'
      path: '/chats'
      fullPath: '/chats'
      preLoaderRoute: typeof AuthenticatedChatsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/players/': {
      id: '/_authenticated/players/'
      path: '/players'
      fullPath: '/players/'
      preLoaderRoute: typeof AuthenticatedPlayersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/play/': {
      id: '/_authenticated/play/'
      path: '/play'
      fullPath: '/play/'
      preLoaderRoute: typeof AuthenticatedPlayIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/tv/game/$gameId': {
      id: '/tv/game/$gameId'
      path: '/tv/game/$gameId'
      fullPath: '/tv/game/$gameId'
      preLoaderRoute: typeof TvGameGameIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/players/$id': {
      id: '/_authenticated/players/$id'
      path: '/players/$id'
      fullPath: '/players/$id'
      preLoaderRoute: typeof AuthenticatedPlayersIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/play/settlements': {
      id: '/_authenticated/play/settlements'
      path: '/play/settlements'
      fullPath: '/play/settlements'
      preLoaderRoute: typeof AuthenticatedPlaySettlementsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/play/account': {
      id: '/_authenticated/play/account'
      path: '/play/account'
      fullPath: '/play/account'
      preLoaderRoute: typeof AuthenticatedPlayAccountRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/play/$id': {
      id: '/_authenticated/play/$id'
      path: '/play/$id'
      fullPath: '/play/$id'
      preLoaderRoute: typeof AuthenticatedPlayIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/nights/new': {
      id: '/_authenticated/nights/new'
      path: '/nights/new'
      fullPath: '/nights/new'
      preLoaderRoute: typeof AuthenticatedNightsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/nights/$id': {
      id: '/_authenticated/nights/$id'
      path: '/nights/$id'
      fullPath: '/nights/$id'
      preLoaderRoute: typeof AuthenticatedNightsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/rsvp': {
      id: '/api/public/hooks/rsvp'
      path: '/api/public/hooks/rsvp'
      fullPath: '/api/public/hooks/rsvp'
      preLoaderRoute: typeof ApiPublicHooksRsvpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/push-reminders': {
      id: '/api/public/hooks/push-reminders'
      path: '/api/public/hooks/push-reminders'
      fullPath: '/api/public/hooks/push-reminders'
      preLoaderRoute: typeof ApiPublicHooksPushRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/new-user': {
      id: '/api/public/hooks/new-user'
      path: '/api/public/hooks/new-user'
      fullPath: '/api/public/hooks/new-user'
      preLoaderRoute: typeof ApiPublicHooksNewUserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/players/walkin/$name': {
      id: '/_authenticated/players/walkin/$name'
      path: '/players/walkin/$name'
      fullPath: '/players/walkin/$name'
      preLoaderRoute: typeof AuthenticatedPlayersWalkinNameRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/play/bj/$id': {
      id: '/_authenticated/play/bj/$id'
      path: '/play/bj/$id'
      fullPath: '/play/bj/$id'
      preLoaderRoute: typeof AuthenticatedPlayBjIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/nights/$id/results': {
      id: '/_authenticated/nights/$id/results'
      path: '/results'
      fullPath: '/nights/$id/results'
      preLoaderRoute: typeof AuthenticatedNightsIdResultsRouteImport
      parentRoute: typeof AuthenticatedNightsIdRoute
    }
    '/_authenticated/nights/$id/edit': {
      id: '/_authenticated/nights/$id/edit'
      path: '/edit'
      fullPath: '/nights/$id/edit'
      preLoaderRoute: typeof AuthenticatedNightsIdEditRouteImport
      parentRoute: typeof AuthenticatedNightsIdRoute
    }
    '/_authenticated/nights/$id/chat': {
      id: '/_authenticated/nights/$id/chat'
      path: '/chat'
      fullPath: '/nights/$id/chat'
      preLoaderRoute: typeof AuthenticatedNightsIdChatRouteImport
      parentRoute: typeof AuthenticatedNightsIdRoute
    }
    '/_authenticated/game/$gameId/tv-control': {
      id: '/_authenticated/game/$gameId/tv-control'
      path: '/game/$gameId/tv-control'
      fullPath: '/game/$gameId/tv-control'
      preLoaderRoute: typeof AuthenticatedGameGameIdTvControlRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedNightsIdRouteChildren {
  AuthenticatedNightsIdChatRoute: typeof AuthenticatedNightsIdChatRoute
  AuthenticatedNightsIdEditRoute: typeof AuthenticatedNightsIdEditRoute
  AuthenticatedNightsIdResultsRoute: typeof AuthenticatedNightsIdResultsRoute
}

const AuthenticatedNightsIdRouteChildren: AuthenticatedNightsIdRouteChildren = {
  AuthenticatedNightsIdChatRoute: AuthenticatedNightsIdChatRoute,
  AuthenticatedNightsIdEditRoute: AuthenticatedNightsIdEditRoute,
  AuthenticatedNightsIdResultsRoute: AuthenticatedNightsIdResultsRoute,
}

const AuthenticatedNightsIdRouteWithChildren =
  AuthenticatedNightsIdRoute._addFileChildren(
    AuthenticatedNightsIdRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedChatsRoute: typeof AuthenticatedChatsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedHistoryRoute: typeof AuthenticatedHistoryRoute
  AuthenticatedHubRoute: typeof AuthenticatedHubRoute
  AuthenticatedLeaderboardRoute: typeof AuthenticatedLeaderboardRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedSettlementsRoute: typeof AuthenticatedSettlementsRoute
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRoute
  AuthenticatedNightsIdRoute: typeof AuthenticatedNightsIdRouteWithChildren
  AuthenticatedNightsNewRoute: typeof AuthenticatedNightsNewRoute
  AuthenticatedPlayIdRoute: typeof AuthenticatedPlayIdRoute
  AuthenticatedPlayAccountRoute: typeof AuthenticatedPlayAccountRoute
  AuthenticatedPlaySettlementsRoute: typeof AuthenticatedPlaySettlementsRoute
  AuthenticatedPlayersIdRoute: typeof AuthenticatedPlayersIdRoute
  AuthenticatedPlayIndexRoute: typeof AuthenticatedPlayIndexRoute
  AuthenticatedPlayersIndexRoute: typeof AuthenticatedPlayersIndexRoute
  AuthenticatedGameGameIdTvControlRoute: typeof AuthenticatedGameGameIdTvControlRoute
  AuthenticatedPlayBjIdRoute: typeof AuthenticatedPlayBjIdRoute
  AuthenticatedPlayersWalkinNameRoute: typeof AuthenticatedPlayersWalkinNameRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedChatsRoute: AuthenticatedChatsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedHistoryRoute: AuthenticatedHistoryRoute,
  AuthenticatedHubRoute: AuthenticatedHubRoute,
  AuthenticatedLeaderboardRoute: AuthenticatedLeaderboardRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedSettlementsRoute: AuthenticatedSettlementsRoute,
  AuthenticatedUsersRoute: AuthenticatedUsersRoute,
  AuthenticatedNightsIdRoute: AuthenticatedNightsIdRouteWithChildren,
  AuthenticatedNightsNewRoute: AuthenticatedNightsNewRoute,
  AuthenticatedPlayIdRoute: AuthenticatedPlayIdRoute,
  AuthenticatedPlayAccountRoute: AuthenticatedPlayAccountRoute,
  AuthenticatedPlaySettlementsRoute: AuthenticatedPlaySettlementsRoute,
  AuthenticatedPlayersIdRoute: AuthenticatedPlayersIdRoute,
  AuthenticatedPlayIndexRoute: AuthenticatedPlayIndexRoute,
  AuthenticatedPlayersIndexRoute: AuthenticatedPlayersIndexRoute,
  AuthenticatedGameGameIdTvControlRoute: AuthenticatedGameGameIdTvControlRoute,
  AuthenticatedPlayBjIdRoute: AuthenticatedPlayBjIdRoute,
  AuthenticatedPlayersWalkinNameRoute: AuthenticatedPlayersWalkinNameRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  McpRoute: McpRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  TvIndexRoute: TvIndexRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  TvGameGameIdRoute: TvGameGameIdRoute,
  ApiPublicHooksNewUserRoute: ApiPublicHooksNewUserRoute,
  ApiPublicHooksPushRemindersRoute: ApiPublicHooksPushRemindersRoute,
  ApiPublicHooksRsvpRoute: ApiPublicHooksRsvpRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
